spring:
  application:
    name: api-gateway #服务名称
  rabbitmq:
    host: localhost
    virtual-host: /virtual_hontek
    username: xiaofan
    password: hontek
zuul:
  routes:
    #完整写法
    # /myProduct/product/list -> /product/product/list
    product:
      path: /myProduct/**
      serviceId: product
      #自定义敏感头
      sensitiveHeaders :
#    #简单写法
#    product: /myProduct/**
  #排除指定路径
  ignored-patterns:
    - /**/product/listForOrder
    - /**/product/decrStock
